# Practica 39 - Operaciones con pandas sobre un 'json nested'

In [4]:
import json

nested_json_1 = {
  "companies": [
    {
      "company": "Tech Solutions",
      "employees": [
        {
          "name": "John Doe",
          "age": 30,
          "address": {
            "street": "123 Main St",
            "city": "New York",
            "zipcode": "10001"
          },
          "skills": ["Python", "Data Analysis"],
          "salary": 3450
        },
        {
          "name": "Jane Smith",
          "age": 25,
          "address": {
            "street": "456 Market St",
            "city": "San Francisco",
            "zipcode": "94105"
          },
          "skills": ["JavaScript", "React"],
          "salary": 2800
        },
        {
          "name": "Mike Johnson",
          "age": 35,
          "address": {
            "street": "789 Broadway",
            "city": "Los Angeles",
            "zipcode": "90015"
          },
          "skills": ["Java", "Spring"],
          "salary": 4200
        }
      ]
    },
    {
      "company": "Innovative Apps",
      "employees": [
        {
          "name": "Alice Brown",
          "age": 28,
          "address": {
            "street": "101 First Ave",
            "city": "Seattle",
            "zipcode": "98101"
          },
          "skills": ["Ruby", "Rails"],
          "salary": 3100
        },
        {
          "name": "Bob White",
          "age": 32,
          "address": {
            "street": "202 Second Ave",
            "city": "Austin",
            "zipcode": "73301"
          },
          "skills": ["PHP", "Laravel"],
          "salary": 2300
        }
      ]
    },
    {
      "company": "Cloud Services",
      "employees": [
        {
          "name": "Charlie Green",
          "age": 29,
          "address": {
            "street": "303 Third St",
            "city": "Chicago",
            "zipcode": "60601"
          },
          "skills": ["AWS", "Azure"],
          "salary": 3700
        },
        {
          "name": "Dana Blue",
          "age": 27,
          "address": {
            "street": "404 Fourth St",
            "city": "Miami",
            "zipcode": "33101"
          },
          "skills": ["GCP", "Docker"],
          "salary": 2700
        }
      ]
    },
    {
      "company": "AI Innovations",
      "employees": [
        {
          "name": "Eva Black",
          "age": 33,
          "address": {
            "street": "505 Fifth Ave",
            "city": "Boston",
            "zipcode": "02101"
          },
          "skills": ["TensorFlow", "Keras"],
          "salary": 4500
        },
        {
          "name": "Frank White",
          "age": 36,
          "address": {
            "street": "606 Sixth Ave",
            "city": "Denver",
            "zipcode": "80201"
          },
          "skills": ["PyTorch", "SciKit-Learn"],
          "salary": 5100
        }
      ]
    },
    {
      "company": "Cyber Security Inc",
      "employees": [
        {
          "name": "George Brown",
          "age": 31,
          "address": {
            "street": "707 Seventh St",
            "city": "Houston",
            "zipcode": "77001"
          },
          "skills": ["Network Security", "Penetration Testing"],
          "salary": 3900
        },
        {
          "name": "Hannah White",
          "age": 26,
          "address": {
            "street": "808 Eighth St",
            "city": "Dallas",
            "zipcode": "75201"
          },
          "skills": ["Cryptography", "SIEM"],
          "salary": 3400
        }
      ]
    },
    {
      "company": "Fintech Solutions",
      "employees": [
        {
          "name": "Ivan Black",
          "age": 30,
          "address": {
            "street": "909 Ninth Ave",
            "city": "Charlotte",
            "zipcode": "28201"
          },
          "skills": ["Blockchain", "Smart Contracts"],
          "salary": 3600
        },
        {
          "name": "Judy White",
          "age": 28,
          "address": {
            "street": "1010 Tenth Ave",
            "city": "Orlando",
            "zipcode": "32801"
          },
          "skills": ["Finance", "Machine Learning"],
          "salary": 2900
        }
      ]
    },
    {
      "company": "Healthcare IT",
      "employees": [
        {
          "name": "Kyle Brown",
          "age": 34,
          "address": {
            "street": "1111 Eleventh Ave",
            "city": "Philadelphia",
            "zipcode": "19101"
          },
          "skills": ["EMR", "EHR"],
          "salary": 4300
        },
        {
          "name": "Laura White",
          "age": 29,
          "address": {
            "street": "1212 Twelfth Ave",
            "city": "Phoenix",
            "zipcode": "85001"
          },
          "skills": ["HL7", "FHIR"],
          "salary": 3200
        }
      ]
    },
    {
      "company": "E-commerce Experts",
      "employees": [
        {
          "name": "Mike Brown",
          "age": 32,
          "address": {
            "street": "1313 Thirteenth Ave",
            "city": "San Diego",
            "zipcode": "92101"
          },
          "skills": ["Magento", "Shopify"],
          "salary": 2900
        },
        {
          "name": "Nina White",
          "age": 27,
          "address": {
            "street": "1414 Fourteenth Ave",
            "city": "Portland",
            "zipcode": "97201"
          },
          "skills": ["WooCommerce", "BigCommerce"],
          "salary": 3800
        }
      ]
    },
    {
      "company": "Game Development Co",
      "employees": [
        {
          "name": "Oscar Brown",
          "age": 30,
          "address": {
            "street": "1515 Fifteenth Ave",
            "city": "Las Vegas",
            "zipcode": "89101"
          },
          "skills": ["Unity", "Unreal Engine"],
          "salary": 4800
        },
        {
          "name": "Pat White",
          "age": 26,
          "address": {
            "street": "1616 Sixteenth Ave",
            "city": "Salt Lake City",
            "zipcode": "84101"
          },
          "skills": ["Game Design", "3D Modeling"],
          "salary": 3600
        }
      ]
    },
    {
      "company": "EdTech Innovations",
      "employees": [
        {
          "name": "Quinn Brown",
          "age": 28,
          "address": {
            "street": "1717 Seventeenth Ave",
            "city": "Minneapolis",
            "zipcode": "55401"
          },
          "skills": ["Moodle", "Canvas"],
          "salary": 3200
        },
        {
          "name": "Riley White",
          "age": 31,
          "address": {
            "street": "1818 Eighteenth Ave",
            "city": "Atlanta",
            "zipcode": "30301"
          },
          "skills": ["Blackboard", "Schoology"],
          "salary": 4000
        }
      ]
    }
  ]
}

# Convertir el diccionario en una cadena JSON
nested_json_str_1 = json.dumps(nested_json_1, indent=4)
print(nested_json_str_1)

{
    "companies": [
        {
            "company": "Tech Solutions",
            "employees": [
                {
                    "name": "John Doe",
                    "age": 30,
                    "address": {
                        "street": "123 Main St",
                        "city": "New York",
                        "zipcode": "10001"
                    },
                    "skills": [
                        "Python",
                        "Data Analysis"
                    ],
                    "salary": 3450
                },
                {
                    "name": "Jane Smith",
                    "age": 25,
                    "address": {
                        "street": "456 Market St",
                        "city": "San Francisco",
                        "zipcode": "94105"
                    },
                    "skills": [
                        "JavaScript",
                        "React"
                    ],
                    "salary": 2800
                },
                {
                    "name": "Mike Johnson",
                    "age": 35,
                    "address": {
                        "street": "789 Broadway",
                        "city": "Los Angeles",
                        "zipcode": "90015"
                    },
                    "skills": [
                        "Java",
                        "Spring"
                    ],
                    "salary": 4200
                }
            ]
        },
        {
            "company": "Innovative Apps",
            "employees": [
                {
                    "name": "Alice Brown",
                    "age": 28,
                    "address": {
                        "street": "101 First Ave",
                        "city": "Seattle",
                        "zipcode": "98101"
                    },
                    "skills": [
                        "Ruby",
                        "Rails"
                    ],
                    "salary": 3100
                },
                {
                    "name": "Bob White",
                    "age": 32,
                    "address": {
                        "street": "202 Second Ave",
                        "city": "Austin",
                        "zipcode": "73301"
                    },
                    "skills": [
                        "PHP",
                        "Laravel"
                    ],
                    "salary": 2300
                }
            ]
        },
        {
            "company": "Cloud Services",
            "employees": [
                {
                    "name": "Charlie Green",
                    "age": 29,
                    "address": {
                        "street": "303 Third St",
                        "city": "Chicago",
                        "zipcode": "60601"
                    },
                    "skills": [
                        "AWS",
                        "Azure"
                    ],
                    "salary": 3700
                },
                {
                    "name": "Dana Blue",
                    "age": 27,
                    "address": {
                        "street": "404 Fourth St",
                        "city": "Miami",
                        "zipcode": "33101"
                    },
                    "skills": [
                        "GCP",
                        "Docker"
                    ],
                    "salary": 2700
                }
            ]
        },
        {
            "company": "AI Innovations",
            "employees": [
                {
                    "name": "Eva Black",
                    "age": 33,
                    "address": {
                        "street": "505 Fifth Ave",
                        "city": "Boston",
                        "zipcode": "02101"
                    },
                    "skills": [
                        "TensorFlow",
                        "Keras"
                    ],
                    "salary": 4500
                },
                {
                    "name": "Frank White",
                    "age": 36,
                    "address": {
                        "street": "606 Sixth Ave",
                        "city": "Denver",
                        "zipcode": "80201"
                    },
                    "skills": [
                        "PyTorch",
                        "SciKit-Learn"
                    ],
                    "salary": 5100
                }
            ]
        },
        {
            "company": "Cyber Security Inc",
            "employees": [
                {
                    "name": "George Brown",
                    "age": 31,
                    "address": {
                        "street": "707 Seventh St",
                        "city": "Houston",
                        "zipcode": "77001"
                    },
                    "skills": [
                        "Network Security",
                        "Penetration Testing"
                    ],
                    "salary": 3900
                },
                {
                    "name": "Hannah White",
                    "age": 26,
                    "address": {
                        "street": "808 Eighth St",
                        "city": "Dallas",
                        "zipcode": "75201"
                    },
                    "skills": [
                        "Cryptography",
                        "SIEM"
                    ],
                    "salary": 3400
                }
            ]
        },
        {
            "company": "Fintech Solutions",
            "employees": [
                {
                    "name": "Ivan Black",
                    "age": 30,
                    "address": {
                        "street": "909 Ninth Ave",
                        "city": "Charlotte",
                        "zipcode": "28201"
                    },
                    "skills": [
                        "Blockchain",
                        "Smart Contracts"
                    ],
                    "salary": 3600
                },
                {
                    "name": "Judy White",
                    "age": 28,
                    "address": {
                        "street": "1010 Tenth Ave",
                        "city": "Orlando",
                        "zipcode": "32801"
                    },
                    "skills": [
                        "Finance",
                        "Machine Learning"
                    ],
                    "salary": 2900
                }
            ]
        },
        {
            "company": "Healthcare IT",
            "employees": [
                {
                    "name": "Kyle Brown",
                    "age": 34,
                    "address": {
                        "street": "1111 Eleventh Ave",
                        "city": "Philadelphia",
                        "zipcode": "19101"
                    },
                    "skills": [
                        "EMR",
                        "EHR"
                    ],
                    "salary": 4300
                },
                {
                    "name": "Laura White",
                    "age": 29,
                    "address": {
                        "street": "1212 Twelfth Ave",
                        "city": "Phoenix",
                        "zipcode": "85001"
                    },
                    "skills": [
                        "HL7",
                        "FHIR"
                    ],
                    "salary": 3200
                }
            ]
        },
        {
            "company": "E-commerce Experts",
            "employees": [
                {
                    "name": "Mike Brown",
                    "age": 32,
                    "address": {
                        "street": "1313 Thirteenth Ave",
                        "city": "San Diego",
                        "zipcode": "92101"
                    },
                    "skills": [
                        "Magento",
                        "Shopify"
                    ],
                    "salary": 2900
                },
                {
                    "name": "Nina White",
                    "age": 27,
                    "address": {
                        "street": "1414 Fourteenth Ave",
                        "city": "Portland",
                        "zipcode": "97201"
                    },
                    "skills": [
                        "WooCommerce",
                        "BigCommerce"
                    ],
                    "salary": 3800
                }
            ]
        },
        {
            "company": "Game Development Co",
            "employees": [
                {
                    "name": "Oscar Brown",
                    "age": 30,
                    "address": {
                        "street": "1515 Fifteenth Ave",
                        "city": "Las Vegas",
                        "zipcode": "89101"
                    },
                    "skills": [
                        "Unity",
                        "Unreal Engine"
                    ],
                    "salary": 4800
                },
                {
                    "name": "Pat White",
                    "age": 26,
                    "address": {
                        "street": "1616 Sixteenth Ave",
                        "city": "Salt Lake City",
                        "zipcode": "84101"
                    },
                    "skills": [
                        "Game Design",
                        "3D Modeling"
                    ],
                    "salary": 3600
                }
            ]
        },
        {
            "company": "EdTech Innovations",
            "employees": [
                {
                    "name": "Quinn Brown",
                    "age": 28,
                    "address": {
                        "street": "1717 Seventeenth Ave",
                        "city": "Minneapolis",
                        "zipcode": "55401"
                    },
                    "skills": [
                        "Moodle",
                        "Canvas"
                    ],
                    "salary": 3200
                },
                {
                    "name": "Riley White",
                    "age": 31,
                    "address": {
                        "street": "1818 Eighteenth Ave",
                        "city": "Atlanta",
                        "zipcode": "30301"
                    },
                    "skills": [
                        "Blackboard",
                        "Schoology"
                    ],
                    "salary": 4000
                }
            ]
        }
    ]
}

In [3]:
import pandas as pd
# Carga el JSON en un DataFrame de pandas
empresas = pd.read_json('companies.json')

# Normaliza los datos JSON
empresas = pd.json_normalize(empresas['companies'], 'employees', ['company'])

# Muestra el DataFrame
print(empresas.head())

           name  age                   skills  salary  address.street  \
0      John Doe   30  [Python, Data Analysis]    3450     123 Main St
1    Jane Smith   25      [JavaScript, React]    2800   456 Market St
2  Mike Johnson   35           [Java, Spring]    4200    789 Broadway
3   Alice Brown   28            [Ruby, Rails]    3100   101 First Ave
4     Bob White   32           [PHP, Laravel]    2300  202 Second Ave

    address.city address.zipcode          company
0       New York           10001   Tech Solutions
1  San Francisco           94105   Tech Solutions
2    Los Angeles           90015   Tech Solutions
3        Seattle           98101  Innovative Apps
4         Austin           73301  Innovative Apps

## Analizar con pandas el archivo anidado `companies.json`

### Rehacer los códigos del notebook `JSON_Limpiar.ipynb` a partir de la `Sección 2- Análisis JSON anidado con Pandas` Desde la celda de código 25.
- Añadir algunos cálculos de estadísticas descriptivas básicas (todos los que ud. quiera) sobre el dataframe final y guardar en otro dataframe dichos cálculos estádisticos. De forma opcional añada algunos 'plots' con matplotlib si quiere.